######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 11 00:52:09 2024
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += threads.cpp
