.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitnet_qt test_bitnet_qt
clean: FORCE
	$(MAKE) -C .. bitnet_qt_clean test_bitnet_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitnet_qt_check
bitnet-qt bitnet-qt.exe: FORCE
	 $(MAKE) -C .. bitnet_qt
apk: FORCE
	$(MAKE) -C .. bitnet_qt_apk
